<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-URDLST5" failures="2" tests="4" name="Default test(failed)(failed)" time="32.517" errors="0" timestamp="2022-10-21T23:07:39 IST">
  <testcase classname="TestCases.FailedTest" name="verifyTitleTest" time="0.031"/>
  <testcase classname="TestCases.FailedTest" name="verifyLoginLogoTest" time="0.102">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TestCases.FailedTest.verifyLoginLogoTest(FailedTest.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginLogoTest -->
  <testcase classname="TestCases.FailedTest" name="verifyUrlTest" time="0.016"/>
  <testcase classname="TestCases.FailedTest" name="verifyBotLogoTest" time="0.088">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TestCases.FailedTest.verifyBotLogoTest(FailedTest.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyBotLogoTest -->
  <testcase classname="TestCases.FailedTest" name="loginToApp1Test" time="0.0">
    <ignored/>
  </testcase> <!-- loginToApp1Test -->
  <testcase classname="TestCases.FailedTest" name="loginToApp2Test" time="0.0">
    <ignored/>
  </testcase> <!-- loginToApp2Test -->
</testsuite> <!-- Default test(failed)(failed) -->
